sudo: false
language: python

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml up -d
  - sleep 10

jobs:
  fast_finish: true
  include:
  # test with custom es index name template
  - python: &latest_py3 3.6
    env: MONGODB=3.2.11 TOXENV=elastic7 ELASTIC7_DOC_MANAGER_ES_INDEX_NAME_TEMPLATE='{db}.{collection}'
  - python: &latest_py3 3.6
    env: MONGODB=3.2.11 TOXENV=elastic7
  - python: &latest_py3 3.6
    env: MONGODB=3.2.11 TOXENV=elastic7
  - python: 3.4
    env: MONGODB=2.6.12 TOXENV=elastic7
  - python: 3.5
    env: MONGODB=2.4.14 TOXENV=elastic7

install:
  - # Install MongoDB
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar -zxf mongodb-linux-x86_64-${MONGODB}.tgz
  - export PATH=${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/:${PATH}
  - mongod --version
  - pip install -U tox tox-venv

script:
  - tox
