sudo: false
language: python

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml up
  - sleep 10

jobs:
  fast_finish: true
  include:
  - python: &latest_py3 3.6
    env: MONGODB=3.2.11 TOXENV=elastic5
  - python: 3.4
    env: MONGODB=2.6.12 TOXENV=elastic2
  - python: 3.5
    env: MONGODB=2.4.14 TOXENV=elastic2
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip

install:
  - # Install MongoDB
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar -zxf mongodb-linux-x86_64-${MONGODB}.tgz
  - export PATH=${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/:${PATH}
  - mongod --version
  - pip install -U tox tox-venv

script:
  - tox
