version: "2"

services:
  es:
    build:
      - context: ./support/es
      - dockerfile: TestDockerfile
    ports:
       - "9200:9200"
    ulimits:
     memlock:
       soft: -1
       hard: -1
     nofile:
       soft: 65536
       hard: 65536
    mem_limit: 1g
    cap_add:
     - IPC_LOCK
    logging:
      driver: none
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - bootstrap.memory_lock=true
     - ES_PUBLISH_HOST=_site_
     - discovery.type=single-node
     - LDAP_USERNAME=ldapservice
     - LDAP_PASSWORD=NOT_SET
     - MINIMUM_MASTER_NODES=1
     - STACK_ID=NOT_SET
     - xpack.security.enabled=false
     - xpack.monitoring.enabled=false
     - xpack.ml.enabled=false
     - xpack.graph.enabled=false
     - xpack.watcher.enabled=false
     - cluster.routing.allocation.disk.threshold_enabled=false
